name: Example Workflow

on:
  push:
    branches:
      - main  # You can change this to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 21f3001303@ds.study.iitm.ac.in
        run: echo "Hello, world!"
